---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ethanliuu-ethanliu-io-v1-operatordemo
  failurePolicy: Fail
  name: moperatordemo.kb.io
  rules:
  - apiGroups:
    - ethanliuu.ethanliu.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - operatordemoes
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ethanliuu-ethanliu-io-v1-operatordemo
  failurePolicy: Fail
  name: voperatordemo.kb.io
  rules:
  - apiGroups:
    - ethanliuu.ethanliu.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - operatordemoes
  sideEffects: None
